CarServices/CarServices/Models/Feedback.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarServices.Models
{
    public class Feedback
    {
        [Key]
        public int FeedbackId { get; set; }

        public string Name { get; set; }

        public string Email { get; set; }


        public string Message { get; set; }






    }
}

CarServices/CarServices/Areas/Admin/Controllers/ServicesPortalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CarServices.Models;
using System.IO;
using System.Web.Hosting;

namespace CarServices.Areas.Admin.Controllers
{




    [Authorize(Roles ="Admin")]
    public class ServicesPortalController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin/ServicesPortal
        public ActionResult Index()
        {
            return View(db.Services.ToList());
        }

        // GET: Admin/ServicesPortal/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = db.Services.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        // GET: Admin/ServicesPortal/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/ServicesPortal/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase file, Service service)
        {



            string path;


            if (file != null)
            {
                var filename = Path.GetFileName(file.FileName);
                var extension = Path.GetExtension(filename).ToLower();
                if (extension == ".jpg" || extension == ".png" || extension == ".jpeg")
                {
                    path = HostingEnvironment.MapPath(Path.Combine("~/Areas/Admin/Images/", filename));
                    file.SaveAs(path);
                    service.ImageUrl = "~/Areas/Admin/Images/" + filename;
                }
                else
                {
                    ModelState.AddModelError("", "Document size must be less then 5MB");
                    return View(service);
                }


                if (ModelState.IsValid)
                {
                    db.Services.Add(service);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }

            return View(service);

        }
        // GET: Admin/ServicesPortal/Edit/5
        public ActionResult Edit(int? id)
        {


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = db.Services.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        // POST: Admin/ServicesPortal/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HttpPostedFileBase file, Service service)
        {

            string path;


            if (file != null)
            {
                var filename = Path.GetFileName(file.FileName);
                var extension = Path.GetExtension(filename).ToLower();
                if (extension == ".jpg" || extension == ".png" || extension == ".jpeg")
                {
                    path = HostingEnvironment.MapPath(Path.Combine("~/Areas/Admin/Images/", filename));
                    file.SaveAs(path);
                    service.ImageUrl = "~/Areas/Admin/Images/" + filename;
                }
                else
                {
                    ModelState.AddModelError("", "Document size must be less then 5MB");
                    return View(service);
                }



                if (ModelState.IsValid)
                {
                    db.Entry(service).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(service);
        }

        // GET: Admin/ServicesPortal/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = db.Services.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        // POST: Admin/ServicesPortal/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Service service = db.Services.Find(id);
            db.Services.Remove(service);
            db.SaveChanges();
            return RedirectToAction("Index");
        }





        // ================= Service Order ===================




        public ActionResult NewOrder()
        {

            var orders = db.Orders.ToList();

            return View(orders);
        }


        // order Detail

        public ActionResult OrderDetails(int id)
        {
            //var services = db.Services.ToList();

            ViewBag.serviceId = id;

            var employeeId = db.Employees.Select(p =>
                new
                {

                    EmployeeId = p.EmployeeId,
                    EmployeeName = p.EmployeeName

                }).ToList();

            //ViewBag.MyId = new SelectList(serviceId, "ServiceID", "ServiceName");

            ViewBag.employeeId = new SelectList(employeeId, "EmployeeId", "EmployeeName");

           
            var orderDetail = db.Orders.Find(id);

            return View(orderDetail);
        }



        [HttpPost]
        public ActionResult OrderDetails(ServiceOrder model)
        {


           var order = db.Orders.Find(model.ServiceOrderID);

            order.EmployeeId = model.EmployeeId;

            db.Entry(order).State = EntityState.Modified;

            db.SaveChanges();

            return RedirectToAction("TotalOrders");
        }




        public ActionResult TotalOrders()
        {

            var orders = db.Orders.Include("Employee").ToList();

            return View(orders);
        }


        public ActionResult TotalOrdersDetail(int id)
        {


            var orderDetail = db.Orders.Include("Employee").Where(o=>o.ServiceOrderID == id).SingleOrDefault();

            return View(orderDetail);
        }


        //============ Feedback =================


        public ActionResult Feedback()
        {

            var feedBack = db.Feedbacks.ToList();

            return View(feedBack);
        }




        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CarServices/CarServices/Areas/Admin/Views/ServicesPortal/Create.cshtml
@model CarServices.Models.Service

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";

}

<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">




                        @using (Html.BeginForm("Create", "ServicesPortal", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))
                        {
                            @Html.AntiForgeryToken()


                            <div class="form-body">
                                <h5 class="card-title" style="text-align:center; background-color:#ffab15; color:#ffffff; font-weight:700">About Product</h5>
                                <hr>

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label"> <b>Service Name </b></label>
                                            @Html.EditorFor(model => model.ServiceName, new { htmlAttributes = new { @class = "form-control", } })
                                            @Html.ValidationMessageFor(model => model.ServiceName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>


                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label"> <b>Service Price </b></label>
                                            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", } })
                                            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                </div>



                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                           

                                            <label class="control-label"> <b> Desription</b></label>

                                            <textarea id="Description" class = "form-control" name="Description"></textarea>
                                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                        </div>
                                    </div>


                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="control-label"> <b>Upload Image </b></label>

                                                @Html.TextBox("file", "", new { type = "file" })

                                            </div>
                                        </div>
                                    </div>








                                    <div class="form-actions m-t-40">
                                        <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Save</button>
                                        @Html.ActionLink("Back to List", "Index", new { @class = "btn btn-dark" })
                                    </div>
                                </div>

                            </div>
                        }

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CarServices/CarServices/Areas/Admin/Views/ServicesPortal/Delete.cshtml
@model CarServices.Models.Service

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_CarServiceLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Service</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ServiceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CarServices/CarServices/Areas/Admin/Views/ServicesPortal/Details.cshtml
@model CarServices.Models.Service

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_CarServiceLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Service</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ServiceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ServiceID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CarServices/CarServices/Areas/Admin/Views/ServicesPortal/Edit.cshtml
@model CarServices.Models.Service



@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";

}

<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">


                        @using (Html.BeginForm("Create", "ServicesPortal", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))
                        {
                            @Html.AntiForgeryToken()


                            <div class="form-body">
                                <h5 class="card-title" style="text-align:center; background-color:#ffab15; color:#ffffff; font-weight:700">About Product</h5>
                                <hr>

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.ServiceID)




                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label"> <b>Service Name </b></label>
                                            @Html.EditorFor(model => model.ServiceName, new { htmlAttributes = new { @class = "form-control", } })
                                            @Html.ValidationMessageFor(model => model.ServiceName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>


                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label"> <b>Service Price </b></label>
                                            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", } })
                                            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                </div>


                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">


                                            <label class="control-label"> <b> Desription</b></label>

                                            <textarea id="Description" class="form-control" name="Description"></textarea>
                                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                        </div>
                                    </div>


                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="control-label"> <b>Upload Image </b></label>

                                                @Html.TextBox("file", "", new { type = "file" })

                                            </div>
                                        </div>
                                    </div>








                                    <div class="form-actions m-t-40">
                                        <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Save</button>
                                        @Html.ActionLink("Back to List", "Index", new { @class = "btn btn-dark" })
                                    </div>
                                </div>

                            </div>
                        }

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CarServices/CarServices/Areas/Admin/Views/ServicesPortal/Feedback.cshtml
@model IEnumerable<CarServices.Models.Feedback>

@{
    ViewBag.Title = "Feedback";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h4 class="text-themecolor">Feedback</h4>
            </div>

        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">

                        <div class="table-responsive">
                            <table class="table product-overview" id="myTable">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Message</th>

                                        
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.Name</td>
                                            <td>@item.Email</td>
                                            <td>@item.Message</td>

                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

CarServices/CarServices/Areas/Admin/Views/ServicesPortal/Index.cshtml
@model IEnumerable<CarServices.Models.Service>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}





<div class="page-wrapper">
   
    <div class="container-fluid">


        <div class="row">


            @foreach (var item in Model)
            {
            <!-- .col -->
                <div class="col-md-6 col-lg-6 col-xlg-4">
                    <div class="card card-body">
                        <div class="row align-items-center">
                            <div class="col-md-4 col-lg-3 text-center">
                                <a href="app-contact-detail.html"><img src="@Url.Content(item.ImageUrl)" alt="user" class="img-circle img-fluid"></a>
                            </div>
                            <div class="col-md-8 col-lg-9">
                                <h3 class="box-title m-b-0">@item.ServiceName</h3>
                                <p>
                                    @item.Description
                                    <br />
                                    <br />
                                    <span>@item.Price</span>
                                    <span style="margin-left:150px">
                                        @Html.ActionLink("Edit", "Edit", new {id= item.ServiceID },  new { @class = "btn btn-dark" })
                                        @Html.ActionLink("Delete", "Delete", new { id = item.ServiceID }, new { @class = "btn btn-dark" })

                                    </span>
                                </p>
                            </div>
                        </div>
                    </div>



                </div>
            }
            <input type="button" value="Test" id="tbtn" />

        </div>
    </div>
</div>

<script>

    $('#tbtn').click(function () {
      
        localStorage.setItem("Nameof Emplyee", "Val");
    });
</script>

CarServices/CarServices/Areas/Admin/Views/ServicesPortal/NewOrder.cshtml
@model IEnumerable<CarServices.Models.ServiceOrder>

@{
    ViewBag.Title = "NewOrder";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h4 class="text-themecolor">All Products</h4>
            </div>

        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">

                        <div class="table-responsive">
                            <table class="table product-overview" id="myTable">
                                <thead>
                                    <tr>
                                        <th>Client Name</th>
                                        <th>Service Name</th>
                                        <th>Mobile#</th>
                                        
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.Name</td>
                                            <td>@item.Service.ServiceName</td>
                                            <td>@item.Mobile</td>
                                         
                                            <td>
                                                <a href="@Url.Action("OrderDetails","ServicesPortal", new { id = item.ServiceOrderID })" class="text-inverse p-r-10" data-toggle="tooltip" title="Details"><i class="fa fa-chevron-circle-right"></i></a>



                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
       
        </div>

    </div>

</div>

CarServices/CarServices/Areas/Admin/Views/ServicesPortal/OrderDetails.cshtml
@model CarServices.Models.ServiceOrder

@{
    ViewBag.Title = "OrderDetails";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}








<!-- Page wrapper  -->
<!-- ============================================================== -->
<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h4 class="text-themecolor">Product Details</h4>
            </div>

        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Info box Content -->
        <!-- ============================================================== -->
        <div class="row">
            <!-- Column -->
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">

                        <div class="row">

                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <h3 class="box-title m-t-40">Complete Info</h3>
                                <div class="table-responsive">

                                    @using (Html.BeginForm("OrderDetails", "ServicesPortal", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                                    {
                                        <table class="table">




                                            @Html.HiddenFor(m => m.ServiceOrderID)

                                            <tbody>
                                                <tr>
                                                    <td width="390">Service Name</td>
                                                    <td> @Model.Service.ServiceName </td>
                                                </tr>
                                                <tr>
                                                    <td>Client Name</td>
                                                    <td>@Model.Name </td>
                                                </tr>
                                                <tr>
                                                    <td>Car's Model</td>
                                                    <td> @Model.VehicleModel </td>
                                                </tr>
                                                <tr>
                                                    <td>Car's Company</td>
                                                    <td> @Model.VehicleCompany </td>
                                                </tr>
                                                <tr>
                                                    <td>Mobile</td>
                                                    <td>@Model.Mobile</td>
                                                </tr>
                                                <tr>
                                                    <td>Location</td>
                                                    <td> @Model.Location </td>
                                                </tr>



                                                <tr>
                                                    <td>Employee</td>
                                                    <td>
                                                        @Html.DropDownList("employeeId", null, htmlAttributes: new { @class = "form-control" ,id= "drpdown" })
                                                    </td>

                                                </tr>




                                            </tbody>


                                        </table>


                                    <input type="submit" value="Send Emplyee" class="btn btn-success"/>

                                    }

                                    <p>
                                        @* @Html.ActionLink("Edit", "Edit", new { id = Model.ID , @class="btn btn-success" }) |*@
                                        @Html.ActionLink("Back to List", "NewOrder")
                                    </p>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

</div>





@*<script>
    $('#Ebtn').click(function () {

     var employeeName =   $('#drpdown :selected').val();

     localStorage.setItem("employeeName", "Val");
    });
</script>*@

CarServices/CarServices/Areas/Admin/Views/ServicesPortal/TotalOrders.cshtml
@model IEnumerable<CarServices.Models.ServiceOrder>
@{
    ViewBag.Title = "TotalOrders";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h4 class="text-themecolor">All Orders</h4>
            </div>

        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">

                        <div class="table-responsive">
                            <table class="table product-overview" id="myTable">
                                <thead>
                                    <tr>
                                        <th>Client Name</th>
                                        <th>Service Name</th>
                                        <th>Mobile#</th>
                                        <th>Employee</th>

                                        <th>Detail</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.Name</td>
                                            <td>@item.Service.ServiceName</td>
                                            <td>@item.Mobile</td>
                                            <td>@item.Employee.EmployeeName</td>
                                            <td>
                                                <a href="@Url.Action("TotalOrdersDetail","ServicesPortal", new { id = item.ServiceOrderID })" class="text-inverse p-r-10" data-toggle="tooltip" title="Details"><i class="fa fa-chevron-circle-right"></i></a>



                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>